GET http://localhost:8080/Products/

###

GET http://localhost:8080/ProductsID/49

###

POST http://localhost:8080/ProductPost/
Content-Type: application/json

{"id": 50, "name": "Chease", "price": 1000}

###

DELETE http://localhost:8080/ProductDel/50